# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewResultsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_selectOutputFolder = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_selectOutputFolder.setObjectName("lineEdit_selectOutputFolder")
        self.horizontalLayout_2.addWidget(self.lineEdit_selectOutputFolder)
        self.pushButton_selectOutputFolder = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_selectOutputFolder.sizePolicy().hasHeightForWidth())
        self.pushButton_selectOutputFolder.setSizePolicy(sizePolicy)
        self.pushButton_selectOutputFolder.setObjectName("pushButton_selectOutputFolder")
        self.horizontalLayout_2.addWidget(self.pushButton_selectOutputFolder)
        self.pushButton_selectOutputFolder.raise_()
        self.lineEdit_selectOutputFolder.raise_()
        self.verticalLayout_4.addWidget(self.frame_2)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_PairwiseEnergies = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_PairwiseEnergies.sizePolicy().hasHeightForWidth())
        self.tab_PairwiseEnergies.setSizePolicy(sizePolicy)
        self.tab_PairwiseEnergies.setMaximumSize(QtCore.QSize(669, 477))
        self.tab_PairwiseEnergies.setObjectName("tab_PairwiseEnergies")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_PairwiseEnergies)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_sourceTargetResEnergies = QtWidgets.QTableWidget(self.tab_PairwiseEnergies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidget_sourceTargetResEnergies.sizePolicy().hasHeightForWidth())
        self.tableWidget_sourceTargetResEnergies.setSizePolicy(sizePolicy)
        self.tableWidget_sourceTargetResEnergies.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tableWidget_sourceTargetResEnergies.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_sourceTargetResEnergies.setObjectName("tableWidget_sourceTargetResEnergies")
        self.tableWidget_sourceTargetResEnergies.setColumnCount(0)
        self.tableWidget_sourceTargetResEnergies.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_sourceTargetResEnergies)
        self.frame_tabPairwiseEnergiesPlots = QtWidgets.QFrame(self.tab_PairwiseEnergies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_tabPairwiseEnergiesPlots.sizePolicy().hasHeightForWidth())
        self.frame_tabPairwiseEnergiesPlots.setSizePolicy(sizePolicy)
        self.frame_tabPairwiseEnergiesPlots.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tabPairwiseEnergiesPlots.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabPairwiseEnergiesPlots.setObjectName("frame_tabPairwiseEnergiesPlots")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_tabPairwiseEnergiesPlots)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addWidget(self.frame_tabPairwiseEnergiesPlots)
        self.tabWidget.addTab(self.tab_PairwiseEnergies, "")
        self.tab_IEM = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_IEM.sizePolicy().hasHeightForWidth())
        self.tab_IEM.setSizePolicy(sizePolicy)
        self.tab_IEM.setMaximumSize(QtCore.QSize(669, 477))
        self.tab_IEM.setObjectName("tab_IEM")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_IEM)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_tabIEM = QtWidgets.QFrame(self.tab_IEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_tabIEM.sizePolicy().hasHeightForWidth())
        self.frame_tabIEM.setSizePolicy(sizePolicy)
        self.frame_tabIEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tabIEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabIEM.setObjectName("frame_tabIEM")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_tabIEM)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2.addWidget(self.frame_tabIEM)
        self.tabWidget.addTab(self.tab_IEM, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.horizontalLayout_3.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_selectOutputFolder.setText(_translate("MainWindow", "Select Output Folder"))
        self.tableWidget_sourceTargetResEnergies.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_PairwiseEnergies), _translate("MainWindow", "Pairwise Energies"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_IEM), _translate("MainWindow", "IEM"))

