# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getresinten/viewResultsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 592)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("clover.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_Top = QtWidgets.QFrame(self.centralwidget)
        self.frame_Top.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_Top.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_Top.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Top.setObjectName("frame_Top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_Top)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_selectOutputFolder = QtWidgets.QLineEdit(self.frame_Top)
        self.lineEdit_selectOutputFolder.setObjectName("lineEdit_selectOutputFolder")
        self.horizontalLayout_2.addWidget(self.lineEdit_selectOutputFolder)
        self.pushButton_selectOutputFolder = QtWidgets.QPushButton(self.frame_Top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_selectOutputFolder.sizePolicy().hasHeightForWidth())
        self.pushButton_selectOutputFolder.setSizePolicy(sizePolicy)
        self.pushButton_selectOutputFolder.setObjectName("pushButton_selectOutputFolder")
        self.horizontalLayout_2.addWidget(self.pushButton_selectOutputFolder)
        self.pushButton_selectOutputFolder.raise_()
        self.lineEdit_selectOutputFolder.raise_()
        self.verticalLayout_2.addWidget(self.frame_Top)
        self.frame_Main = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Main.sizePolicy().hasHeightForWidth())
        self.frame_Main.setSizePolicy(sizePolicy)
        self.frame_Main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Main.setObjectName("frame_Main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_Main)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_PairwiseEnergies = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_PairwiseEnergies.sizePolicy().hasHeightForWidth())
        self.tab_PairwiseEnergies.setSizePolicy(sizePolicy)
        self.tab_PairwiseEnergies.setMinimumSize(QtCore.QSize(800, 0))
        self.tab_PairwiseEnergies.setMaximumSize(QtCore.QSize(10000000, 10000000))
        self.tab_PairwiseEnergies.setObjectName("tab_PairwiseEnergies")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_PairwiseEnergies)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget_sourceTargetResEnergies = QtWidgets.QTableWidget(self.tab_PairwiseEnergies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidget_sourceTargetResEnergies.sizePolicy().hasHeightForWidth())
        self.tableWidget_sourceTargetResEnergies.setSizePolicy(sizePolicy)
        self.tableWidget_sourceTargetResEnergies.setMinimumSize(QtCore.QSize(300, 0))
        self.tableWidget_sourceTargetResEnergies.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tableWidget_sourceTargetResEnergies.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_sourceTargetResEnergies.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_sourceTargetResEnergies.setObjectName("tableWidget_sourceTargetResEnergies")
        self.tableWidget_sourceTargetResEnergies.setColumnCount(0)
        self.tableWidget_sourceTargetResEnergies.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableWidget_sourceTargetResEnergies)
        self.frame_tabPairWiseEnergiesBarPlot = QtWidgets.QFrame(self.tab_PairwiseEnergies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_tabPairWiseEnergiesBarPlot.sizePolicy().hasHeightForWidth())
        self.frame_tabPairWiseEnergiesBarPlot.setSizePolicy(sizePolicy)
        self.frame_tabPairWiseEnergiesBarPlot.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_tabPairWiseEnergiesBarPlot.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_tabPairWiseEnergiesBarPlot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tabPairWiseEnergiesBarPlot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabPairWiseEnergiesBarPlot.setObjectName("frame_tabPairWiseEnergiesBarPlot")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_tabPairWiseEnergiesBarPlot)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3.addWidget(self.frame_tabPairWiseEnergiesBarPlot)
        self.frame_tabPairWiseEnergiesPlots = QtWidgets.QFrame(self.tab_PairwiseEnergies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_tabPairWiseEnergiesPlots.sizePolicy().hasHeightForWidth())
        self.frame_tabPairWiseEnergiesPlots.setSizePolicy(sizePolicy)
        self.frame_tabPairWiseEnergiesPlots.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_tabPairWiseEnergiesPlots.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tabPairWiseEnergiesPlots.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabPairWiseEnergiesPlots.setObjectName("frame_tabPairWiseEnergiesPlots")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_tabPairWiseEnergiesPlots)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3.addWidget(self.frame_tabPairWiseEnergiesPlots)
        self.tabWidget.addTab(self.tab_PairwiseEnergies, "")
        self.tab_IEM = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_IEM.sizePolicy().hasHeightForWidth())
        self.tab_IEM.setSizePolicy(sizePolicy)
        self.tab_IEM.setMinimumSize(QtCore.QSize(400, 0))
        self.tab_IEM.setMaximumSize(QtCore.QSize(669, 477))
        self.tab_IEM.setObjectName("tab_IEM")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_IEM)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_tabIEM = QtWidgets.QFrame(self.tab_IEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_tabIEM.sizePolicy().hasHeightForWidth())
        self.frame_tabIEM.setSizePolicy(sizePolicy)
        self.frame_tabIEM.setMinimumSize(QtCore.QSize(400, 400))
        self.frame_tabIEM.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tabIEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabIEM.setObjectName("frame_tabIEM")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_tabIEM)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5.addWidget(self.frame_tabIEM)
        self.tabWidget.addTab(self.tab_IEM, "")
        self.tab_Network = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_Network.sizePolicy().hasHeightForWidth())
        self.tab_Network.setSizePolicy(sizePolicy)
        self.tab_Network.setMinimumSize(QtCore.QSize(400, 0))
        self.tab_Network.setObjectName("tab_Network")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_Network)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_Network)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_GeneralNetwork = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_GeneralNetwork.sizePolicy().hasHeightForWidth())
        self.tab_GeneralNetwork.setSizePolicy(sizePolicy)
        self.tab_GeneralNetwork.setObjectName("tab_GeneralNetwork")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_GeneralNetwork)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_NetworkParameters = QtWidgets.QFrame(self.tab_GeneralNetwork)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_NetworkParameters.sizePolicy().hasHeightForWidth())
        self.frame_NetworkParameters.setSizePolicy(sizePolicy)
        self.frame_NetworkParameters.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_NetworkParameters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_NetworkParameters.setObjectName("frame_NetworkParameters")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_NetworkParameters)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.frame_NetworkParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMaximumSize(QtCore.QSize(500, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 8, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_NetworkParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(500, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 9, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_NetworkParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMaximumSize(QtCore.QSize(500, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_NetworkParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 30))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_NetworkParameters)
        self.scrollArea_NetworkParametersPlot = QtWidgets.QScrollArea(self.tab_GeneralNetwork)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_NetworkParametersPlot.sizePolicy().hasHeightForWidth())
        self.scrollArea_NetworkParametersPlot.setSizePolicy(sizePolicy)
        self.scrollArea_NetworkParametersPlot.setMinimumSize(QtCore.QSize(0, 150))
        self.scrollArea_NetworkParametersPlot.setMaximumSize(QtCore.QSize(16777215, 400))
        self.scrollArea_NetworkParametersPlot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_NetworkParametersPlot.setWidgetResizable(True)
        self.scrollArea_NetworkParametersPlot.setObjectName("scrollArea_NetworkParametersPlot")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 902, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 150))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame_NetworkParameters.raise_()
        self.frame_NetworkParameters.raise_()
        self.scrollArea_NetworkParametersPlot.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea_NetworkParametersPlot)
        self.tabWidget_2.addTab(self.tab_GeneralNetwork, "")
        self.tab_ShortestPaths = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_ShortestPaths.sizePolicy().hasHeightForWidth())
        self.tab_ShortestPaths.setSizePolicy(sizePolicy)
        self.tab_ShortestPaths.setObjectName("tab_ShortestPaths")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_ShortestPaths)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_ShortestPathsTop = QtWidgets.QFrame(self.tab_ShortestPaths)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_ShortestPathsTop.sizePolicy().hasHeightForWidth())
        self.frame_ShortestPathsTop.setSizePolicy(sizePolicy)
        self.frame_ShortestPathsTop.setMinimumSize(QtCore.QSize(500, 10))
        self.frame_ShortestPathsTop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_ShortestPathsTop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_ShortestPathsTop.setObjectName("frame_ShortestPathsTop")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_ShortestPathsTop)
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_ShortestPathsTop)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.comboBox_SourceResidue = QtWidgets.QComboBox(self.frame_ShortestPathsTop)
        self.comboBox_SourceResidue.setObjectName("comboBox_SourceResidue")
        self.horizontalLayout_6.addWidget(self.comboBox_SourceResidue)
        self.label_2 = QtWidgets.QLabel(self.frame_ShortestPathsTop)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox_TargetResidue = QtWidgets.QComboBox(self.frame_ShortestPathsTop)
        self.comboBox_TargetResidue.setObjectName("comboBox_TargetResidue")
        self.horizontalLayout_6.addWidget(self.comboBox_TargetResidue)
        self.pushButton_findShortestPaths = QtWidgets.QPushButton(self.frame_ShortestPathsTop)
        self.pushButton_findShortestPaths.setObjectName("pushButton_findShortestPaths")
        self.horizontalLayout_6.addWidget(self.pushButton_findShortestPaths)
        self.verticalLayout_7.addWidget(self.frame_ShortestPathsTop)
        self.tableWidget_ShortestPaths = QtWidgets.QTableWidget(self.tab_ShortestPaths)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidget_ShortestPaths.sizePolicy().hasHeightForWidth())
        self.tableWidget_ShortestPaths.setSizePolicy(sizePolicy)
        self.tableWidget_ShortestPaths.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_ShortestPaths.setObjectName("tableWidget_ShortestPaths")
        self.tableWidget_ShortestPaths.setColumnCount(0)
        self.tableWidget_ShortestPaths.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget_ShortestPaths)
        self.tabWidget_2.addTab(self.tab_ShortestPaths, "")
        self.verticalLayout_6.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_Network, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_4.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.frame_Main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "gRINN: View Results"))
        self.pushButton_selectOutputFolder.setText(_translate("MainWindow", "Select Output Folder"))
        self.tableWidget_sourceTargetResEnergies.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_PairwiseEnergies), _translate("MainWindow", "Pairwise Energies"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_IEM), _translate("MainWindow", "IEM"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose plot..."))
        self.comboBox.setItemText(1, _translate("MainWindow", "Degree"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Betweenness Centrality"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Number of nodes:</p><p>Number of edges:</p><p>Average degree:</p><p>Density:<br/></p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Choose data to use as edge weights..."))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Mean Interaction Energy"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Total Residue Correlation"))
        self.pushButton.setText(_translate("MainWindow", "Export Network to File..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_GeneralNetwork), _translate("MainWindow", "General"))
        self.label.setText(_translate("MainWindow", "Source Residue"))
        self.label_2.setText(_translate("MainWindow", "Target Residue"))
        self.pushButton_findShortestPaths.setText(_translate("MainWindow", "Find"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_ShortestPaths), _translate("MainWindow", "Shortest Paths"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Network), _translate("MainWindow", "Network Analysis"))

