# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getResIntEnGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(801, 500)
        MainWindow.setMinimumSize(QtCore.QSize(801, 500))
        MainWindow.setMaximumSize(QtCore.QSize(801, 500))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.doubleSpinBox_preFilteringCutoff = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_preFilteringCutoff.setGeometry(QtCore.QRect(180, 250, 62, 24))
        self.doubleSpinBox_preFilteringCutoff.setProperty("value", 20.0)
        self.doubleSpinBox_preFilteringCutoff.setObjectName(_fromUtf8("doubleSpinBox_preFilteringCutoff"))
        self.doubleSpinBox_filteringCutoff = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_filteringCutoff.setGeometry(QtCore.QRect(460, 250, 62, 24))
        self.doubleSpinBox_filteringCutoff.setProperty("value", 12.0)
        self.doubleSpinBox_filteringCutoff.setObjectName(_fromUtf8("doubleSpinBox_filteringCutoff"))
        self.lineEdit_residueGroup1 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_residueGroup1.setGeometry(QtCore.QRect(250, 180, 271, 24))
        self.lineEdit_residueGroup1.setObjectName(_fromUtf8("lineEdit_residueGroup1"))
        self.lineEdit_residueGroup2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_residueGroup2.setGeometry(QtCore.QRect(250, 210, 271, 24))
        self.lineEdit_residueGroup2.setObjectName(_fromUtf8("lineEdit_residueGroup2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 180, 241, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 210, 241, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 250, 171, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 250, 151, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 290, 441, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.doubleSpinBox_filteringPercent = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_filteringPercent.setGeometry(QtCore.QRect(460, 290, 62, 24))
        self.doubleSpinBox_filteringPercent.setProperty("value", 10.0)
        self.doubleSpinBox_filteringPercent.setObjectName(_fromUtf8("doubleSpinBox_filteringPercent"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 340, 81, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.plainTextEdit_dcdStride = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_dcdStride.setGeometry(QtCore.QRect(180, 330, 61, 31))
        self.plainTextEdit_dcdStride.setObjectName(_fromUtf8("plainTextEdit_dcdStride"))
        self.spinBox_numProcessors = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_numProcessors.setGeometry(QtCore.QRect(460, 340, 62, 24))
        self.spinBox_numProcessors.setProperty("value", 4)
        self.spinBox_numProcessors.setObjectName(_fromUtf8("spinBox_numProcessors"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 340, 151, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton_Calculate = QtGui.QPushButton(self.centralwidget)
        self.pushButton_Calculate.setGeometry(QtCore.QRect(540, 10, 251, 51))
        self.pushButton_Calculate.setObjectName(_fromUtf8("pushButton_Calculate"))
        self.progressBar_filtering = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_filtering.setGeometry(QtCore.QRect(540, 210, 251, 23))
        self.progressBar_filtering.setProperty("value", 0)
        self.progressBar_filtering.setObjectName(_fromUtf8("progressBar_filtering"))
        self.progressBar_calculation = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_calculation.setGeometry(QtCore.QRect(540, 260, 251, 23))
        self.progressBar_calculation.setProperty("value", 0)
        self.progressBar_calculation.setObjectName(_fromUtf8("progressBar_calculation"))
        self.progressBar_preFiltering = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_preFiltering.setGeometry(QtCore.QRect(540, 160, 251, 23))
        self.progressBar_preFiltering.setProperty("value", 0)
        self.progressBar_preFiltering.setObjectName(_fromUtf8("progressBar_preFiltering"))
        self.pushButton_Stop = QtGui.QPushButton(self.centralwidget)
        self.pushButton_Stop.setEnabled(False)
        self.pushButton_Stop.setGeometry(QtCore.QRect(540, 70, 251, 51))
        self.pushButton_Stop.setObjectName(_fromUtf8("pushButton_Stop"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(540, 140, 251, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(540, 190, 251, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(540, 240, 251, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(520, 0, 20, 461))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.lineEdit_pdb = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_pdb.setGeometry(QtCore.QRect(10, 10, 271, 21))
        self.lineEdit_pdb.setObjectName(_fromUtf8("lineEdit_pdb"))
        self.lineEdit_psf = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_psf.setGeometry(QtCore.QRect(10, 40, 271, 21))
        self.lineEdit_psf.setObjectName(_fromUtf8("lineEdit_psf"))
        self.lineEdit_dcd = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_dcd.setGeometry(QtCore.QRect(10, 70, 271, 21))
        self.lineEdit_dcd.setObjectName(_fromUtf8("lineEdit_dcd"))
        self.lineEdit_outputFolder = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_outputFolder.setGeometry(QtCore.QRect(10, 100, 271, 21))
        self.lineEdit_outputFolder.setObjectName(_fromUtf8("lineEdit_outputFolder"))
        self.lineEdit_namd2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_namd2.setGeometry(QtCore.QRect(10, 130, 271, 21))
        self.lineEdit_namd2.setObjectName(_fromUtf8("lineEdit_namd2"))
        self.pushButton_browsePDB = QtGui.QPushButton(self.centralwidget)
        self.pushButton_browsePDB.setGeometry(QtCore.QRect(290, 10, 231, 21))
        self.pushButton_browsePDB.setObjectName(_fromUtf8("pushButton_browsePDB"))
        self.pushButton_browsePSF = QtGui.QPushButton(self.centralwidget)
        self.pushButton_browsePSF.setGeometry(QtCore.QRect(290, 40, 231, 21))
        self.pushButton_browsePSF.setObjectName(_fromUtf8("pushButton_browsePSF"))
        self.pushButton_browseDCD = QtGui.QPushButton(self.centralwidget)
        self.pushButton_browseDCD.setGeometry(QtCore.QRect(290, 70, 231, 21))
        self.pushButton_browseDCD.setObjectName(_fromUtf8("pushButton_browseDCD"))
        self.pushButton_browseOutputFolder = QtGui.QPushButton(self.centralwidget)
        self.pushButton_browseOutputFolder.setGeometry(QtCore.QRect(290, 100, 231, 21))
        self.pushButton_browseOutputFolder.setObjectName(_fromUtf8("pushButton_browseOutputFolder"))
        self.pushButton_BrowseNAMD = QtGui.QPushButton(self.centralwidget)
        self.pushButton_BrowseNAMD.setGeometry(QtCore.QRect(290, 130, 231, 21))
        self.pushButton_BrowseNAMD.setObjectName(_fromUtf8("pushButton_BrowseNAMD"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lineEdit_residueGroup1.setText(_translate("MainWindow", "resid 0 to 10", None))
        self.lineEdit_residueGroup2.setText(_translate("MainWindow", "resid 0 to 10", None))
        self.label.setText(_translate("MainWindow", "Selection 1 (use ProDy selection syntax)", None))
        self.label_2.setText(_translate("MainWindow", "Selection 1 (use ProDy selection syntax)", None))
        self.label_3.setText(_translate("MainWindow", "Pre-filtering distance cutoff:", None))
        self.label_4.setText(_translate("MainWindow", "Filtering distance cutoff:", None))
        self.label_5.setText(_translate("MainWindow", "Select only those residue pairs which are closer than the filtering distance cutoff to each other for at least the following percent of the trajectory:", None))
        self.label_6.setText(_translate("MainWindow", "DCD stride", None))
        self.plainTextEdit_dcdStride.setPlainText(_translate("MainWindow", "100", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Number of processors</p></body></html>", None))
        self.pushButton_Calculate.setText(_translate("MainWindow", "CALCULATE", None))
        self.progressBar_preFiltering.setFormat(_translate("MainWindow", "%p%", None))
        self.pushButton_Stop.setText(_translate("MainWindow", "STOP", None))
        self.label_11.setText(_translate("MainWindow", "Pre-filtering progress", None))
        self.label_12.setText(_translate("MainWindow", "Filtering progress", None))
        self.label_13.setText(_translate("MainWindow", "Calculation progress", None))
        self.lineEdit_pdb.setText(_translate("MainWindow", "test.pdb", None))
        self.lineEdit_psf.setText(_translate("MainWindow", "test.psf", None))
        self.lineEdit_dcd.setText(_translate("MainWindow", "test.dcd", None))
        self.lineEdit_outputFolder.setText(_translate("MainWindow", "getResIntEn_output", None))
        self.lineEdit_namd2.setText(_translate("MainWindow", "NAMD_2.12b1/namd2", None))
        self.pushButton_browsePDB.setText(_translate("MainWindow", "Browse for PDB File", None))
        self.pushButton_browsePSF.setText(_translate("MainWindow", "Browse for PSF File", None))
        self.pushButton_browseDCD.setText(_translate("MainWindow", "Browse for DCD File", None))
        self.pushButton_browseOutputFolder.setText(_translate("MainWindow", "Output Folder", None))
        self.pushButton_BrowseNAMD.setText(_translate("MainWindow", "Browse for NAMD Executable", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))

