# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getResIntEnGUI.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 400)
        MainWindow.setMinimumSize(QtCore.QSize(801, 0))
        MainWindow.setMaximumSize(QtCore.QSize(801, 400))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.doubleSpinBox_filteringCutoff = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_filteringCutoff.setGeometry(QtCore.QRect(460, 250, 62, 24))
        self.doubleSpinBox_filteringCutoff.setProperty("value", 12.0)
        self.doubleSpinBox_filteringCutoff.setObjectName("doubleSpinBox_filteringCutoff")
        self.lineEdit_residueGroup1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_residueGroup1.setGeometry(QtCore.QRect(250, 180, 271, 24))
        self.lineEdit_residueGroup1.setObjectName("lineEdit_residueGroup1")
        self.lineEdit_residueGroup2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_residueGroup2.setGeometry(QtCore.QRect(250, 210, 271, 24))
        self.lineEdit_residueGroup2.setObjectName("lineEdit_residueGroup2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 180, 241, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 210, 241, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 250, 151, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 250, 91, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox_filteringPercent = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_filteringPercent.setGeometry(QtCore.QRect(190, 250, 62, 24))
        self.doubleSpinBox_filteringPercent.setProperty("value", 10.0)
        self.doubleSpinBox_filteringPercent.setObjectName("doubleSpinBox_filteringPercent")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 81, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_dcdStride = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_dcdStride.setGeometry(QtCore.QRect(190, 280, 61, 31))
        self.plainTextEdit_dcdStride.setObjectName("plainTextEdit_dcdStride")
        self.spinBox_numProcessors = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numProcessors.setGeometry(QtCore.QRect(460, 290, 62, 24))
        self.spinBox_numProcessors.setProperty("value", 4)
        self.spinBox_numProcessors.setObjectName("spinBox_numProcessors")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 290, 151, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_Calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Calculate.setGeometry(QtCore.QRect(540, 10, 251, 51))
        self.pushButton_Calculate.setObjectName("pushButton_Calculate")
        self.progressBar_filtering = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_filtering.setGeometry(QtCore.QRect(540, 160, 251, 23))
        self.progressBar_filtering.setProperty("value", 0)
        self.progressBar_filtering.setObjectName("progressBar_filtering")
        self.progressBar_calculation = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_calculation.setGeometry(QtCore.QRect(540, 230, 251, 23))
        self.progressBar_calculation.setProperty("value", 0)
        self.progressBar_calculation.setObjectName("progressBar_calculation")
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setEnabled(False)
        self.pushButton_Stop.setGeometry(QtCore.QRect(540, 70, 251, 51))
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(540, 140, 251, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(540, 210, 251, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(520, 10, 20, 461))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_pdb = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pdb.setGeometry(QtCore.QRect(10, 10, 271, 21))
        self.lineEdit_pdb.setObjectName("lineEdit_pdb")
        self.lineEdit_psf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_psf.setGeometry(QtCore.QRect(10, 40, 271, 21))
        self.lineEdit_psf.setObjectName("lineEdit_psf")
        self.lineEdit_dcd = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dcd.setGeometry(QtCore.QRect(10, 70, 271, 21))
        self.lineEdit_dcd.setObjectName("lineEdit_dcd")
        self.lineEdit_outputFolder = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_outputFolder.setGeometry(QtCore.QRect(10, 100, 271, 21))
        self.lineEdit_outputFolder.setObjectName("lineEdit_outputFolder")
        self.lineEdit_namd2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_namd2.setGeometry(QtCore.QRect(10, 130, 271, 21))
        self.lineEdit_namd2.setObjectName("lineEdit_namd2")
        self.pushButton_browsePDB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browsePDB.setGeometry(QtCore.QRect(290, 10, 231, 21))
        self.pushButton_browsePDB.setObjectName("pushButton_browsePDB")
        self.pushButton_browsePSF = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browsePSF.setGeometry(QtCore.QRect(290, 40, 231, 21))
        self.pushButton_browsePSF.setObjectName("pushButton_browsePSF")
        self.pushButton_browseDCD = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browseDCD.setGeometry(QtCore.QRect(290, 70, 231, 21))
        self.pushButton_browseDCD.setObjectName("pushButton_browseDCD")
        self.pushButton_browseOutputFolder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browseOutputFolder.setGeometry(QtCore.QRect(290, 100, 231, 21))
        self.pushButton_browseOutputFolder.setObjectName("pushButton_browseOutputFolder")
        self.pushButton_BrowseNAMD = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BrowseNAMD.setGeometry(QtCore.QRect(290, 130, 231, 21))
        self.pushButton_BrowseNAMD.setObjectName("pushButton_BrowseNAMD")
        self.checkBox_interactionCorrelation = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interactionCorrelation.setGeometry(QtCore.QRect(190, 320, 331, 21))
        self.checkBox_interactionCorrelation.setObjectName("checkBox_interactionCorrelation")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_residueGroup1.setText(_translate("MainWindow", "resid 0 to 10"))
        self.lineEdit_residueGroup2.setText(_translate("MainWindow", "resid 0 to 10"))
        self.label.setText(_translate("MainWindow", "Selection 1 (use ProDy selection syntax)"))
        self.label_2.setText(_translate("MainWindow", "Selection 1 (use ProDy selection syntax)"))
        self.label_4.setText(_translate("MainWindow", "Filtering distance cutoff:"))
        self.label_5.setText(_translate("MainWindow", "Percent cutoff"))
        self.label_6.setText(_translate("MainWindow", "DCD stride"))
        self.plainTextEdit_dcdStride.setPlainText(_translate("MainWindow", "100"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Number of processors</p></body></html>"))
        self.pushButton_Calculate.setText(_translate("MainWindow", "CALCULATE"))
        self.pushButton_Stop.setText(_translate("MainWindow", "STOP"))
        self.label_12.setText(_translate("MainWindow", "Filtering progress"))
        self.label_13.setText(_translate("MainWindow", "Calculation progress"))
        self.lineEdit_pdb.setText(_translate("MainWindow", "test.pdb"))
        self.lineEdit_psf.setText(_translate("MainWindow", "test.psf"))
        self.lineEdit_dcd.setText(_translate("MainWindow", "test.dcd"))
        self.lineEdit_outputFolder.setText(_translate("MainWindow", "getResIntEn_output"))
        self.lineEdit_namd2.setText(_translate("MainWindow", "NAMD_2.12b1/namd2"))
        self.pushButton_browsePDB.setText(_translate("MainWindow", "Browse for PDB File"))
        self.pushButton_browsePSF.setText(_translate("MainWindow", "Browse for PSF File"))
        self.pushButton_browseDCD.setText(_translate("MainWindow", "Browse for DCD File"))
        self.pushButton_browseOutputFolder.setText(_translate("MainWindow", "Output Folder"))
        self.pushButton_BrowseNAMD.setText(_translate("MainWindow", "Browse for NAMD Executable"))
        self.checkBox_interactionCorrelation.setText(_translate("MainWindow", "Calculate residue interaction correlation as well"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))

